using System.Security.Cryptography;
using System.Text;

namespace Argon2DotnetFast.CommonPasswordsGenerator;

// Also compiled into Argon2DotnetFast.Tests, which rebuilds the set and compares it with the committed data.
internal static class CommonPasswordSet
{
    internal const string SourceName = "xato-net-10-million-passwords-10000.txt";
    internal const string SourceSha256 = "c63d5e4ccc31344d662583cc39ca4bd5bd20517ff1d24501f0c4e0c22d9b722a";
    internal const int Budget = 10240;
    private const int RemainderBits = 12;

    internal sealed record Result(int Count, int MaxLength, ulong[] Codes, byte[] Stream);

    // Folded entries in rank order, repeats dropped. An empty line is the empty password.
    internal static List<byte[]> ReadEntries(string dataDirectory)
    {
        string path = Path.Combine(dataDirectory, SourceName);
        byte[] file = File.ReadAllBytes(path);
        string actual = Convert.ToHexString(SHA256.HashData(file)).ToLowerInvariant();
        if (actual != SourceSha256)
            throw new InvalidDataException($"{path} has SHA-256 {actual}, expected {SourceSha256}.");

        var entries = new List<byte[]>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        int start = 0;
        while (start < file.Length)
        {
            int end = Array.IndexOf(file, (byte)'\n', start);
            if (end < 0) end = file.Length;
            byte[] entry = file[start..end];
            CommonPasswords.Fold(entry);
            if (seen.Add(Convert.ToHexString(entry))) entries.Add(entry);
            start = end + 1;
        }
        return entries;
    }

    // Every prefix length is encoded, from the longest down, because all codes move when Count changes.
    internal static Result Build(List<byte[]> entries)
    {
        ulong[] digests = entries.Select(entry => CommonPasswords.Digest(entry)).ToArray();
        for (int count = entries.Count; count > 0; count--)
        {
            ulong[] codes = new ulong[count];
            for (int i = 0; i < count; i++) codes[i] = CommonPasswords.Map(digests[i], count);
            Array.Sort(codes);
            if (Bits(codes) <= Budget * 8L)
                return new Result(count, entries.Take(count).Max(entry => entry.Length), codes, Encode(codes));
        }
        throw new InvalidDataException("Not even one entry fits the budget.");
    }

    internal static string Source(Result result)
    {
        var text = new StringBuilder();
        text.Append("// <auto-generated>\n");
        text.Append($"// Written by src/Argon2DotnetFast.CommonPasswords.Generator from {SourceName}\n");
        text.Append($"// (SHA-256 {SourceSha256}). Run the generator instead of editing this file.\n");
        text.Append("// </auto-generated>\n\n");
        text.Append("namespace Argon2DotnetFast.Internal;\n\n");
        text.Append("internal static class CommonPasswordData\n{\n");
        text.Append("    // The top entries of the source list after A-Z folding, repeats dropped.\n");
        text.Append($"    internal const int Count = {result.Count};\n\n");
        text.Append("    // The longest of those entries, in UTF-8 bytes.\n");
        text.Append($"    internal const int MaxLength = {result.MaxLength};\n\n");
        text.Append($"    // {result.Stream.Length} bytes: the sorted codes as Rice-coded gaps with {RemainderBits}-bit remainders,\n");
        text.Append("    // most significant bit first.\n");
        text.Append("    internal static ReadOnlySpan<byte> Stream => new byte[]\n    {\n");
        for (int i = 0; i < result.Stream.Length; i += 16)
        {
            IEnumerable<string> row = result.Stream.Skip(i).Take(16).Select(b => $"0x{b:X2}");
            text.Append("        ").Append(string.Join(", ", row)).Append(",\n");
        }
        text.Append("    };\n}\n");
        return text.ToString();
    }

    private static long Bits(ulong[] sortedCodes)
    {
        long bits = 0;
        ulong previous = 0;
        foreach (ulong code in sortedCodes)
        {
            bits += (long)((code - previous) >> RemainderBits) + 1 + RemainderBits;
            previous = code;
        }
        return bits;
    }

    // Unary quotient in one-bits, a zero bit, then the low bits, most significant bit first.
    private static byte[] Encode(ulong[] sortedCodes)
    {
        byte[] stream = new byte[(Bits(sortedCodes) + 7) / 8];
        long bit = 0;
        ulong previous = 0;
        foreach (ulong code in sortedCodes)
        {
            ulong gap = code - previous;
            previous = code;
            for (ulong quotient = gap >> RemainderBits; quotient > 0; quotient--) Set(stream, bit++);
            bit++;
            for (int j = RemainderBits - 1; j >= 0; j--, bit++)
                if (((gap >> j) & 1) != 0) Set(stream, bit);
        }
        return stream;
    }

    private static void Set(byte[] stream, long bit) => stream[bit >> 3] |= (byte)(0x80 >> (int)(bit & 7));
}
